
services:
  web_api:
    container_name: omgdb_web_api
    build: 
      context: .
      dockerfile: omgdb_web_api.Dockerfile
    image: omgdb_web_api:latest   
    ports:
      - "80:80"
      - "443:443"
    environment:
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${OMGDB_ASPNETCORE_Kestrel__Certificates__Default__Password}
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/OMGDBapp.pfx"
      ASPNETCORE_ConnectionStrings_DefaultConnection: ${ASPNETCORE_ConnectionStrings_DefaultConnection}
      JWT_SECRET: ${OMGDB_API_JWT_SECRET}
    volumes:
      - ./certs:/https:ro    
    depends_on:
      - "postgres"

  postgres:
    container_name: OMGDB-pg
    build: 
      context: .
      dockerfile: omdb_pg_pgtap.Dockerfile
    image: omgdb_pg_pgtap:latest  
    hostname: localhost
    ports:
      - "5532:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${OMGDB_POSTGRES_PASSWORD}
      POSTGRES_DB: OMGDB_db
    volumes:
      - citp_portfolio_project_postgres-data-OMGDB:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: OMGDB-pgadmin
    image: dpage/pgadmin4:8.12.0
    depends_on:
      - postgres
    ports:
      - "5550:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${OMGDB_PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${OMGDB_PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - f2eeebaad83afb9c13152f407eb12ed40738fe9517018482bb7a4392e87fe442:/var/lib/pgadmin  
    restart: unless-stopped

volumes:
  citp_portfolio_project_postgres-data-OMGDB:
    external: true
  f2eeebaad83afb9c13152f407eb12ed40738fe9517018482bb7a4392e87fe442:
    external: true